PLAT-115992: Support A11y for Checkbox, CheckboxItem, and RadioItem
enactjs/agate pull request #326
Opened 2020-08-26 01:14 UTC by ybsung

Support A11y for Checkbox, CheckboxItem, and RadioItem

Additional Consideration
- Remove `labelPosition` knob in Checkbox sampler because it is not related with Checkbox but related with CheckboxItem
- Wrap CheckboxBase with Toggleable(I'm not sure, but like Sandstone), Spottable(to spot via 5-way keys), and Skinnable( to apply a skin) for a Checkbox

Enact-DCO-1.0-Signed-off-by: YB Sung (yb.sung@lge.com)

2020-08-26 06:26 UTC, seunghoh requested changes
As we discussed, let's not to change the structure and support only in the CheckboxItem just like moonstone as of now.

2020-08-27 08:35 UTC, seunghoh approved these changes

2020-08-27 08:36 UTC, seunghoh commented
LGTM

2020-08-28 05:53 UTC, MikyungKim approved these changes
LGTM

2020-08-28 05:53 UTC, merged