Added more component views for screenshot test
enactjs/agate pull request #382
Opened 2020-10-16 13:46 UTC by stanca-pop-lgp

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Agate - added more component views for screenshot test

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
* Root Cause
=> There were only 16 component views for screenshot test in https://github.com/enactjs/agate/tree/develop/tests/screenshot/apps/components. But there are 45 public ui components.
 Solution -> Added more component views for screenshot test

### Links
[//]: # (Related issues, references)
PLAT-122911

### Comments

2020-10-16 14:00 UTC, adrian-cocoara-lgp approved these changes

2020-10-20 04:12 UTC, ybsung requested changes
![image](https://user-images.githubusercontent.com/4239873/96539347-d4a74c80-12d5-11eb-87c0-2d2d77800180.png)

`MediaPlayer` screenshot wasn't created well. Please check screenshot files in tests/screenshot/dist/screenshots/reference or screen after running `npm run test-ss`.

2020-10-20 08:29 UTC, ybsung approved these changes
LGTM

2020-11-03 05:56 UTC, jeonghee27 commented on tests/screenshot/apps/components/SliderButton.js
> +	<SliderButton>{[]}</SliderButton>,
I think the buttons should be displayed.
Currently,  only meaningless things are displayed.

2020-11-03 13:08 UTC, merged