Feature/plat 124936
enactjs/agate pull request #400
Opened 2020-11-09 15:33 UTC by stanca-pop-lgp

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Need to align the architecture of the Button and Marquee components in Agate to follow the model from Sandstone.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Button:

- added Marquee
- added iconPosition prop
- updated defaultProps
- added IconButtonDecorator to replace minWidth computed
- added TooltipDecorator

Marquee:

- added new component for Marquee (to support rtl)
- added screenshot tests

Both Button and Marquee: 
- updated/created screenshot tests
- created Test Cases on JIRA

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-124936

### Comments

2020-11-09 16:27 UTC, daniel-stoian-lgp approved these changes

2020-11-09 16:28 UTC, adrian-cocoara-lgp approved these changes

2020-11-10 12:11 UTC, ybsung requested changes
Hello @stanca-pop-lgp 

Great job!!! The overall direction of progress seems to have progressed well in the direction the SWP engineers thought.

I found that we needed to cleanup some code in Sandstone while reviewing the PR. We might need to fix it in a separate issue after merging this PR.

The `Marquee` sampler is quite different from the one in Sandstone. Did you make it from scratch or bright some code from other samples? It would be helpful to review your code by knowing it.

I just reviewed the PR based on the code. I need to review it more for the area verifying the Button behavior after mixing agate original props and agate new props. Please feel free to update the PR while I'm reviewing it more.

2020-11-11 02:46 UTC, ybsung commented
![image](https://user-images.githubusercontent.com/4239873/98759004-71f82b00-2413-11eb-87af-4d959e25e067.png)

In `ar-SA`, the badge position is still on the top-right (not on the top-left).

2020-11-11 02:48 UTC, ybsung commented
![image](https://user-images.githubusercontent.com/4239873/98759146-c7343c80-2413-11eb-9af3-5a9bf3f11c68.png)

The Tooptip position of the Button is incorrect.

2020-11-11 02:54 UTC, ybsung commented
NOTE:
`joinedPosition` prop has 'left', 'center', and 'right' values. It looks same in LTR and RTL. But it think we might reverse the look. To do it, we might change the values to 'start', 'center', and 'end'. It is out of the scope in the PR and we shouldn't break APIs for now. Let's discuss it in another issue.

2020-11-11 03:39 UTC, ybsung requested changes
I wrote more comments.
Some comments are not related with `Sync up`, but we hope that we could polish our Agate components while syncing up.
CC : @seunghoh, @MikyungKim , @0x64 , @jeonghee27 , @jeongran1230

2020-11-11 03:39 UTC, ybsung commented on Button/Button.js
> +		 * @default true
I don't know why @default is true here? It might make a developer confused. Let's remove it.
NOTE: Need to fix in sandstone

2020-11-11 03:39 UTC, ybsung commented on Marquee/Marquee.js
> +	 * @public
My expectation for documentation order would
```
	 * @see {@link ui/Marquee.Marquee}
	 * @class Marquee
	 * @memberof agate/Marquee
	 * @extends ui/Marquee.Marquee
	 * @mixes (if needed)
	 * @ui
	 * @public
```
Let's fix them in this file.

CC: @jeongran1230

2020-11-11 03:39 UTC, ybsung commented on Marquee/Marquee.js
> +	 * A block element which will marquee its contents
We need a `.` at the end of the sentence.

NOTE: Need to fix in sandstone

2020-11-11 03:39 UTC, ybsung commented on Button/Button.js
> +		className: ({animateOnRender, backgroundOpacity, highlighted, iconOnly, iconPosition, joinedPosition, selected, type, size, styler}) => styler.append(
In my opinion, `joinedPosition` and `type` (with `grid` value) props couldn't be used at the same time. We might warn it if app developers.

Here is the way how to warn
```
import warning from 'warning';

	computed: {
		bgImage: ({placeholder, src}) => {
			const imageSrc = selectSrc(src) || placeholder;
			warning(imageSrc, 'Image requires that either the "placeholder" or "src" props be specified.');
			if (!imageSrc) return null;
			return placeholder && imageSrc !== placeholder ? `url("${imageSrc}"), url("${placeholder}")` : `url("${imageSrc}")`;
		},
```
https://github.com/enactjs/enact/blob/develop/packages/ui/Image/Image.js#L156

2020-11-11 03:39 UTC, ybsung commented on Button/Button.js
> +		className: ({animateOnRender, backgroundOpacity, highlighted, iconOnly, iconPosition, joinedPosition, selected, type, size, styler}) => styler.append(
In addition, `iconOnly` can't be used with `joinedPosition` and `type` and `highlighted` can't be used with `selected`.

2020-11-11 04:37 UTC, ybsung commented on CHANGELOG.md
> +- `agate/Button` iconOnly, iconPosition, minWidth props
I don't think that we share internal logic changes to app developers. So we might not need the following logs.
```
- `agate/Button` marquee decorator
- `agate/Button` tooltip decorator
```

Component names or prop names should be wrapped with ``.

```suggestion
- `agate/Button` prop `iconOnly`, `iconPosition`, and `minWidth`
- `agate/Marquee` component

### Fixed

- `agate/Button` to marquee when focused
- `agate/Button` to show a tooltip when hovered
```

2020-11-11 04:37 UTC, ybsung commented on CHANGELOG.md
> +- `agate/Button` minWidth computed with IconButtonDecorator HoC
Let's skip this log.

2020-11-13 15:47 UTC, stanca-pop-lgp commented
> ![image](https://user-images.githubusercontent.com/4239873/98759146-c7343c80-2413-11eb-9af3-5a9bf3f11c68.png)
> 
> The Tooptip position of the Button is incorrect.

We suggest that we create a separate task for this issue, as it does not concern the Button component, but the TooltipDecorator.

2020-11-13 16:10 UTC, stanca-pop-lgp commented on Marquee/Marquee.js
> +export default Marquee;
Hello, @ybsung! I tried pushing the changes, but I am not allowed. I got this: `remote: Permission to enactjs/docs.git denied to stanca-pop-lgp.
fatal: unable to access 'https://github.com/enactjs/docs.git/': The requested URL returned error: 403
`

2020-11-16 12:54 UTC, ybsung commented
Hello @stanca-pop-lgp 
Are you ready for this PR review?
For docs repo, we're discussing.

2020-11-17 06:46 UTC, ybsung commented
NOTE:
![image](https://user-images.githubusercontent.com/4239873/99355595-eafff280-28eb-11eb-9248-acf772fdfe18.png)

It seems that the button text is clipped. Let's fix it in another issue.

2020-11-17 06:49 UTC, ybsung commented on CHANGELOG.md
> +- `agate/Button` `checkPropsIncompatibility` function to warn props incompatibility
`checkPropsIncompatibility` is not `agate/Button/`'s prop. It might be better to remove it.

2020-11-17 10:39 UTC, ybsung approved these changes
LGTM

2020-11-17 13:10 UTC, stanca-pop-lgp commented
> NOTE:
> ![image](https://user-images.githubusercontent.com/4239873/99355595-eafff280-28eb-11eb-9248-acf772fdfe18.png)
> 
> It seems that the button text - `|Click me|` is clipped. Let's fix it in another issue.

Could you please give me more details about how you tested this? I can't seem to reproduce it. I wrote "| Click me |" in the children case and switched to Silicon and it looks fine. Thank you!!
![image](https://user-images.githubusercontent.com/63341832/99394104-04eb0680-28e7-11eb-879c-45704880e6ad.png)

2020-11-18 01:49 UTC, ybsung commented
Hi @stanca-pop-lgp 

> Could you please give me more details about how you tested this? I can't seem to reproduce it. I wrote "| Click me |" in the children case and switched to Silicon and it looks fine. Thank you!!

Hmm. I can't reproduce it now. I might verify the Button incorrectly. Let's skip it. Thanks for letting me know.

2020-11-19 08:09 UTC, jeonghee27 approved these changes
It's a huge modification. I'd like to divide tickets next time. Greate job.

2020-11-19 08:09 UTC, merged