PLAT-126343:  Add UI tests for agate/Dropdown
enactjs/agate pull request #415
Opened 2020-11-20 16:14 UTC by stanca-pop-lgp

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- added UI tests for agate/Dropdown

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-126343

### Comments

2020-11-23 09:14 UTC, daniel-stoian-lgp approved these changes
LGTM

2020-11-23 09:19 UTC, adrian-cocoara-lgp approved these changes

2020-11-24 07:28 UTC, MikyungKim commented on tests/ui/apps/Dropdown/Dropdown-View.js
> +		<Dropdown id="dropdownSelected" defaultSelected={1} title="Selected">
I think this missed from the spec. Are you going to test this component too?

2020-11-24 07:34 UTC, MikyungKim commented on tests/ui/specs/Dropdown/Dropdown-specs.js
> +		beforeEach(function () {
I think we don't need this..

2020-11-24 07:35 UTC, MikyungKim commented on tests/ui/specs/Dropdown/Dropdown-specs.js
> +		beforeEach(function () {
This one also.

2020-11-24 07:37 UTC, MikyungKim commented on tests/ui/specs/Dropdown/Dropdown-specs.js
> +	describe('in scroller', function () {
How about we separate the spec for `in scroller`?
I think you could refer to FixedPopupPanels from sandstone.

2020-11-24 07:40 UTC, MikyungKim commented on tests/ui/specs/Dropdown/Dropdown-specs.js
> +			browser.pause(1000);
I'm not sure this is good. 🤔

2020-11-24 07:43 UTC, MikyungKim commented on tests/ui/specs/Dropdown/Dropdown-specs.js
> +		it('should have title visible when focusing button via 5-way', function () {
Is this case related to the dropdown itself? I think it's for scroller...

```suggestion
		it('should scroll into view when navigating dropdown via 5-way', function () {
```

2020-11-24 07:44 UTC, MikyungKim requested changes
Good! Please find my comments.
And I think we need more test cases for selecting values.

2020-11-29 23:10 UTC, MikyungKim approved these changes
LGTM

2020-12-01 07:22 UTC, jeonghee27 commented
I feel that the verification script is somewhat lacking.
If there is a disabled element, it would be better if there is script to verify disabled function.
Hopefully the test script will be added after Agate TC is added more.

2020-12-01 07:23 UTC, merged