PLAT-127676: Agate-Popup: added buttons knob in sampler and fixed 2 styling bugs for silicon
enactjs/agate pull request #446
Opened 2020-12-11 11:05 UTC by daniel-stoian-lgp

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- added `buttons` knob for Popup sampler
- removed the qa-sampler for "Popup with buttons" because it became became obsolete 
2 styiling bugs fixes:
- popup with no title, but with close button: the <buttons> left-right edges was not the same as the popup(like in Zeplin)
- popup with no title, but with close button: the popup contet was overlapping the close button

### Links
[//]: # (Related issues, references)
PLAT-127676

### Comments

2020-12-11 11:15 UTC, stanca-pop-lgp approved these changes

2020-12-11 11:27 UTC, adrian-cocoara-lgp approved these changes

2020-12-16 05:36 UTC, ybsung requested changes
Could you find my comments?

2020-12-16 07:53 UTC, daniel-stoian-lgp commented on samples/sampler/stories/default/Popup.js
> +			<Button>Cancel</Button>
well, it might be up for the consumer to decide the order. the <buttons> prop supports that

2020-12-16 09:08 UTC, ybsung approved these changes
LGTM

2021-01-12 06:36 UTC, merged