PLAT-121900: Fix to close expanded dropdown on escape key press
enactjs/agate pull request #449
Opened 2020-12-14 15:18 UTC by stanca-pop-lgp

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Issue: Expanded dropdown is not closed on Escape key press.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Solution: Added `escKeyPressed` function and `handleKeyDown` handler to forward onClick on Toggleable. Pressing Escape closes the dropdown.

### Links
[//]: # (Related issues, references)
PLAT-121900

### Comments

2020-12-14 15:23 UTC, daniel-stoian-lgp approved these changes

2020-12-18 04:03 UTC, MikyungKim commented on CHANGELOG.md
> +- `agate/Dropdown` to support close expanded dropdown with 5-way key
```suggestion
- `agate/Dropdown` to support closing dropdown with back key
```

2020-12-18 04:50 UTC, MikyungKim commented on Dropdown/Dropdown.js
> +		escKeyPressed = (event) => {
We have `forKey` from `@enact/core/handle` for this purpose.

2020-12-18 04:51 UTC, MikyungKim commented on Dropdown/Dropdown.js
> +			this.escKeyPressed,
Let's `import {forKey} from '@enact/core/handle';` and replace this to `forKey('cancel')`.

2020-12-18 05:04 UTC, MikyungKim commented on Dropdown/Dropdown.js
> +			this.escKeyPressed,
Also, we need to add
```
// Add keymap for escape key
add('cancel', 27);
```
above line 63 after importing `add` like `import {add} from '@enact/core/keymap';`

2020-12-18 05:05 UTC, MikyungKim requested changes
Good work. some clean up needed.

2020-12-22 01:27 UTC, MikyungKim approved these changes
Lint, unit, and ui tests are passed locally.
:lgtm:

2020-12-22 09:26 UTC, merged