PLAT-129511: Added unit tests for Panels
enactjs/agate pull request #451
Opened 2020-12-15 15:05 UTC by daniel-stoian-lgp

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
 - Added ui tests for Panels

### Links
[//]: # (Related issues, references)
PLAT-129511
### Comments

2020-12-15 16:19 UTC, stanca-pop-lgp approved these changes

2020-12-21 08:48 UTC, seunghoh requested changes
Can you add more test cases so that we can cover props as many as possible (ideally all props)? I understand you referred to Sandstone TCs and yes, we also need to update Sandstone TCs to cover all functions

2020-12-24 06:41 UTC, seunghoh commented on samples/sampler/stories/default/Panels.js
> +			orientation={select('orientation', ['horizontal', 'vertical'], Config)}
Good catch! 👍

2020-12-24 07:01 UTC, seunghoh approved these changes

2020-12-24 07:05 UTC, merged