PLAT-129751: ProgressBar, IncrementSlider, Slider Architecture sync
enactjs/agate pull request #466
Opened 2020-12-22 13:47 UTC by daniel-stoian-lgp

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- added ProgressBarTooltip components
- ProgressBar: added tooltip, highlighted, orientation="radial" props
- Slider: - added tooltip functionality
- IncrementSlider:  - added tooltip functionality
- Updates unit tests / ui tests / screenshot tests

### Links
[//]: # (Related issues, references)
PLAT-129751

### Comments

2020-12-22 16:05 UTC, adrian-cocoara-lgp commented on IncrementSlider/IncrementSlider.js
> +		 * @default false
Is this needed?

2020-12-22 16:19 UTC, adrian-cocoara-lgp approved these changes
LGTM

2020-12-23 14:13 UTC, stanca-pop-lgp approved these changes
Superb! Great work!

2021-03-02 09:11 UTC, 0x64 requested changes

2021-03-02 09:11 UTC, 0x64 commented on CHANGELOG.md
> +- `agate/ProgressBarTooltip` component
`agate/SliderTooltip` is also added.

2021-03-02 09:23 UTC, 0x64 commented
Synced up on `develop` branch to resolve conflicts by #494

2021-03-03 09:48 UTC, daniel-stoian-lgp commented on tests/screenshot/apps/components/ProgressBar.js
> +	<ProgressBar progress={0.75} />,
Thanks for the tip. I will add more ss-tests for all 3 components

2021-03-04 04:21 UTC, 0x64 approved these changes
:lgtm:

2021-03-04 06:34 UTC, MikyungKim commented
Did you add orientation="radial" props to `ProgressBar`? I'm not seeing the change.

2021-03-04 06:48 UTC, daniel-stoian-lgp commented
> Did you add orientation="radial" props to `ProgressBar`? I'm not seeing the change.

I had the intention at the beggining of the implementation, but after some discussions back in December regarding what we should bring to Agate in the architecture sync, and because there was no use case for this orientation in Zeplin, I removed that part from this PR. 
Sorry, I forgot to update the PR description. I will update it now :)

2021-03-04 08:06 UTC, MikyungKim commented on ProgressBar/ProgressBar.js
>   * @module agate/ProgressBar
I'm seeing `backgroundProgress` in the @example but it seems we don't have it.

2021-03-04 08:12 UTC, MikyungKim reviewed
@daniel-stoian-lgp , For props `backgroundProgress` and `hightlighted` of ProgressBar, don't we need to sync this?

2021-03-04 15:45 UTC, daniel-stoian-lgp commented
> @daniel-stoian-lgp , For props `backgroundProgress` and `hightlighted` of ProgressBar, don't we need to sync this?

hmmm, I see the IncrementSlider already has a backgroundProgress prop which is not used in the sampler. So I think ProgressBar would need this sync.
I'll take care of there two props :)

2021-03-05 08:04 UTC, daniel-stoian-lgp commented
Travis fails because of failing unit tests after #522 was merged

2021-03-05 08:09 UTC, MikyungKim commented
@daniel-stoian-lgp Please git merge the latest develop on your branch. It will fix the travis.

2021-03-05 08:23 UTC, daniel-stoian-lgp commented
> @daniel-stoian-lgp Please git merge the latest develop on your branch. It will fix the travis.

Thanks :)

2021-03-05 08:58 UTC, MikyungKim commented on CHANGELOG.md
> +- `agate/ProgressBarTooltip` props `highlighted` and `backgroundProgress`
```suggestion
- `agate/ProgressBar` props `highlighted` and `backgroundProgress`
```

2021-03-05 09:00 UTC, MikyungKim commented on Slider/Slider.js
> +		// /**
Why these lines are commented out?

2021-03-05 09:02 UTC, daniel-stoian-lgp commented on Slider/Slider.js
> +		// /**
my mistake

2021-03-08 08:15 UTC, MikyungKim approved these changes
:shipit:

2021-03-08 08:16 UTC, merged