PLAT-121001: Agate Docs: Write missing documentation for components
enactjs/agate pull request #499
Opened 2021-01-28 09:27 UTC by paul-beldean-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
- Some components didn't have documentation

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- Added missing documentation for components

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-121001

### Comments

Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

2021-01-28 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enactjs/agate?pullRequest=499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/enactjs/agate?pullRequest=499) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enactjs/agate?pullRequest=499) it.</sub>

2021-01-28 09:39 UTC, daniel-stoian-lgp commented on FullscreenPopup/FullscreenPopup.js
>  		type: PropTypes.string
```suggestion
		type: PropTypes.oneOf(['slide', 'clip', 'fade']),
```

2021-01-28 09:49 UTC, daniel-stoian-lgp reviewed
Congratulations for your first PR!

Just a few adjustments are required

2021-01-28 09:49 UTC, daniel-stoian-lgp commented on Panels/TabbedPanels.js
> +		* Components to be included after the tabs.
maybe 'Nodes' is a better word, instead of 'Components'

2021-01-28 09:49 UTC, daniel-stoian-lgp commented on Panels/TabbedPanels.js
> +		* Components to be included before the tabs.
here also. Nodes instead of Components

2021-01-28 09:49 UTC, daniel-stoian-lgp commented on Panels/TabbedPanels.js
> +		 * Disable tabbed panels transitions.
```suggestion
		 * Disables tabbed panels transition animations.
```

2021-01-28 10:45 UTC, daniel-stoian-lgp approved these changes
LGTM

2021-01-28 14:56 UTC, adrian-cocoara-lgp commented on Drawer/Drawer.js
> +		 * Disable drawer transitions.
```suggestion
		 * Disables drawer transition animation.
```

2021-01-28 15:46 UTC, adrian-cocoara-lgp commented on PopupMenu/PopupMenu.js
> +		 * Disable popup menu transitions.
```suggestion
		 * Disables popup menu transition animation.
```

2021-01-28 15:47 UTC, adrian-cocoara-lgp commented on SliderButton/SliderButton.js
> +		 * @type {String[]}
```suggestion
		 * @type {String}
```

2021-02-03 07:45 UTC, jeongran1230 commented
In Agate Drawer.js, There is no description about `orientation` property. If absent, please add it.
```
defaultProps: {
   ...
  orientation: 'vertical'
}
```

2021-02-03 08:06 UTC, jeongran1230 commented
`defaultProp` does not exist for `IncrementSliderButtonBase` component
```
defaultProps: 
    orientation: 'horizontal',
    role: 'list',
    size: 'large'
```

2021-02-03 08:19 UTC, jeongran1230 commented
'closeButtonAriaLabel' property should be added in defaultProp object in TabbedPanelBase component (TabbedPanel.js)
```
defaultProps: {
+   closeButtonAriaLabel: 'Exit app'
    index:0
```

2021-02-03 15:27 UTC, paul-beldean-lgp commented
> In Agate Drawer.js, There is no description about `orientation` property. If absent, please add it.
> 
> ```
> defaultProps: {
>    ...
>   orientation: 'vertical'
> }
> ```

The drawer doesn't seem to look ok with orientation="horizontal" so I think we could remove it from defaultProps and add it as a prop for the Layout inside the render. Would that be ok?

2021-02-03 23:55 UTC, jeongran1230 commented
> The drawer doesn't seem to look ok with orientation="horizontal" so I think we could remove it from defaultProps and add it as a prop for the Layout inside the render. Would that be ok?

I understood what you intended. I think it is more clear to define `orientation` as private prop by using @private tag like below.
```
propTypes: /** @lends agate/Drawer.DrawerBase.prototype */ {
   ...
         /**
		 * Orientation description..
		 *
		 * @type {String}
		 * @default 'vertical'
		 * @private
		 */
		orientation: PropTypes.oneOf(['horizontal', 'vertical']),
```

2021-02-05 05:51 UTC, jeongran1230 commented
I found there is no description for props in `TabGroupBase` class. Is it missed or having reason?

2021-02-05 05:55 UTC, jeongran1230 commented
Please add the following code: 
```--- a/Drawer/Drawer.js
+++ b/Drawer/Drawer.js
@@ -25,6 +25,7 @@ import componentCss from './Drawer.module.less';
  *
  * @class DrawerBase
  * @memberof agate/Drawer
+ * @extends ui/Transition.Transition
  * @ui
  * @public
  */
diff --git a/IncrementSlider/IncrementSliderButton.js b/IncrementSlider/IncrementSliderButton.js
index b0e06b3..a951257 100644
--- a/IncrementSlider/IncrementSliderButton.js
+++ b/IncrementSlider/IncrementSliderButton.js
@@ -14,6 +14,7 @@ import componentCss from './IncrementSliderButton.module.less';
  *
  * @class IncrementSliderButton
  * @memberof agate/IncrementSlider
+ * @extends agate/Button
  * @ui
  * @private
  */
```

2021-02-05 07:53 UTC, paul-beldean-lgp commented
> I found there is no description for props in `TabGroupBase` class. Is it missed or having reason?

It was added in this pull request that was just merged: https://github.com/enactjs/agate/pull/488

2021-02-09 04:28 UTC, jeongran1230 commented
Congratulations your 1st PR.

2021-02-09 04:28 UTC, jeongran1230 commented
LGTM

2021-03-10 04:54 UTC, seunghoh commented
@stanca-pop-lgp You have one pending review. Do you need more time to review?

2021-03-10 06:21 UTC, seunghoh requested changes
@paul-beldean-lgp Would you fix parse errors? There are lots of parsing errors when I try `npm run parse -- --extra-repos enactjs/agate#feature/PLAT-121001`

2021-03-11 01:24 UTC, seunghoh approved these changes

2021-03-11 01:24 UTC, merged