PLAT-129636: [Agate] Apply max-width and marquee in Arc family components
enactjs/agate pull request #514
Opened 2021-02-15 10:13 UTC by paul-beldean-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
slotCenter content was too big and overflowed the arc component

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added Marquee and max-width to make it display correctly

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-129636

### Comments

Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

2021-02-15 10:16 UTC, daniel-stoian-lgp commented on styles/variables-base.less
> +@agate-fanspeedcontrol-icon-line-height: 2rem;
use pixel values in the code. Agate has a resolution independence system that will adapt this value to the screen size.

2021-02-15 10:17 UTC, daniel-stoian-lgp commented on styles/variables-base.less
> +@agate-winddirectioncontrol-icon-margin: 0px;
0 values don't need px

2021-02-15 10:22 UTC, daniel-stoian-lgp commented
This PR needs a changelog entry

2021-02-15 15:42 UTC, daniel-stoian-lgp approved these changes

2021-03-04 06:11 UTC, MikyungKim requested changes
I agree to add max-width to `slotCenter`, but for Marquee, I hope we could fix qa-a11y sample.

2021-03-12 01:46 UTC, MikyungKim approved these changes
👏 LGTM!

2021-03-16 07:10 UTC, seunghoh approved these changes
LGTM 👍 
The further consideration(even not related to this PR): This is A11y sample but there's no way to read out `slotCenter`. Please consider how can we support to read `slotCenter` with 5-way key when the ArcPicker, ArcSlider get focused.

2021-03-16 07:10 UTC, merged