WRO-13689: Panel - fix console warnings
enactjs/agate pull request #688
Opened 2022-10-20 13:54 UTC by andreitirlalge

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Fixed console warnings for Agate Panel by modifying storybook's ThemeEnvironment and Panel.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
The spotlightId and hideChildren warnings are fixed.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Further investigation on how the changes made in storybook's ThemeEnvironment and Panel may affect the components.

### Links
[//]: # (Related issues, references)
WRO-13689

### Comments
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

2022-10-21 14:31 UTC, stanca-pop-lgp requested changes

2022-10-21 14:31 UTC, stanca-pop-lgp commented on samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
> +		</Scroller>);
```suggestion
	const panelSample = (sample.type.displayName === 'Panel');

	const allSkinsSample =
		<Scroller>
			{Object.keys(skins).map((skin) => (
				<SkinFrame skin={skins[skin]} key={skin}>
					<Cell size="20%" component={Heading}>{skin}</Cell>
					<Cell style={{minHeight: panelSample ? ri.scaleToRem(300) : ''}}>{sample}</Cell>
				</SkinFrame>
			))}
		</Scroller>;

	const showAllSkinsSample = panelSample ? <Panel>{allSkinsSample}</Panel> : allSkinsSample;
```

2022-10-21 14:31 UTC, stanca-pop-lgp commented on samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
> +			{showAllSkins ? allSkinsSample : sample}
```suggestion
			{showAllSkins ? showAllSkinsSample : sample}
```

2022-10-21 14:31 UTC, stanca-pop-lgp commented on samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
>  };
Please remove empty line below.

2022-10-21 14:31 UTC, stanca-pop-lgp commented on samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
>  import {Row, Column, Cell} from '@enact/ui/Layout';
```suggestion
import {Cell, Column, Row} from '@enact/ui/Layout';
```

2022-10-21 14:31 UTC, stanca-pop-lgp commented on samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
>  import {Panels, Panel} from '@enact/agate/Panels';
```suggestion
import {Panel, Panels} from '@enact/agate/Panels';
```

2022-10-21 14:31 UTC, stanca-pop-lgp commented on samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
> +import Header from '@enact/agate/Header';
Please remove this import if you apply my suggestions.

2022-10-21 15:06 UTC, stanca-pop-lgp approved these changes
LGTM

2022-10-27 02:36 UTC, jeonghee27 commented
When I test on my local env, the console error was deleted just by modifying the Panel.js file.
Why do we need to fix ThemeEnviroment.js?

2022-10-27 02:37 UTC, jeonghee27 commented
Please check Travis result

2022-10-30 23:33 UTC, jeonghee27 approved these changes
LGTM

2022-10-30 23:33 UTC, merged