WRP-3064: Increase code coverage for IncrementSlider, Slider, ProgressBar
enactjs/agate pull request #702
Opened 2022-11-24 13:46 UTC by andreitirlalge

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Increase code coverage for IncrementSlider, Slider, ProgressBar related modules.

Code coverage increase
IncrementSlider(overall) 43.83% -> 93.15%
IncrementSlider.js 63.41% -> 100%
utils.js 0% -> 80.76%

ProgressBar(overall) 72.88% -> 88.13%
ProgressBarTooltip.js 68% -> 86%

Slider(overall) 88% -> 93.15%
SliderBehaviourDecorator.js 82.81% -> 90.62%
utils.js 96.15% -> 100%

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-3064

### Comments
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

2022-11-24 16:00 UTC, stanca-pop-lgp requested changes

2022-11-24 16:00 UTC, stanca-pop-lgp commented on Slider/tests/Slider-specs.js
> +		render(<Slider onChange={spy} active defaultValue={50} knobStep={2} />);
Please sort props.

2022-11-25 11:31 UTC, stanca-pop-lgp approved these changes
LGTM

2022-11-25 13:11 UTC, daniel-stoian-lgp approved these changes

2022-11-25 13:12 UTC, daniel-stoian-lgp commented
Note for the next reviewer: Does this PR need a changelog for the import fix in incrementSlider.js?

2022-12-14 10:40 UTC, daniel-stoian-lgp approved these changes

2022-12-14 10:40 UTC, merged