WRP-3058: Increase code coverage for Arc, ArcPicker, ArcSlider, TemperatureControl
enactjs/agate pull request #703
Opened 2022-11-24 18:06 UTC by adrian-cocoara-lgp

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Increased code coverage

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-3058

### Comments

2022-11-25 11:53 UTC, stanca-pop-lgp requested changes

2022-11-25 11:53 UTC, stanca-pop-lgp commented on Arc/tests/Arc-specs.js
> +		render(<Arc data-testid="arc" color="#00FF00" />);
Please sort props.

2022-11-25 11:53 UTC, stanca-pop-lgp commented on Arc/tests/Arc-specs.js
> +
Please remove empty line.

2022-11-25 11:53 UTC, stanca-pop-lgp commented on ArcSlider/tests/ArcSlider-specs.js
> +import {valueToAngle, angleToValue} from '../utils';
Please sort import.

2022-11-25 11:53 UTC, stanca-pop-lgp commented on TemperatureControl/tests/TemperatureControl-specs.js
> +
Please remove empty line.

2022-11-25 13:51 UTC, alexandrumorariu approved these changes
LGTM

2022-12-14 12:06 UTC, daniel-stoian-lgp approved these changes

2022-12-14 12:06 UTC, merged