WRP-3083: Increased code coverage for VirtualList
enactjs/agate pull request #705
Opened 2022-12-05 15:33 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Increased code coverage for VirtualList

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-3083

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian [daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com)

2022-12-06 09:28 UTC, daniel-stoian-lgp commented
I also tried to add a test where focus was moved outside the VirtualList and returned to an item inside it in order to hit the function **calculatePositionOnFocus()** inisde useThemeVirtualList.js
Although testing this scenario live in a sample does hit the function, in the tests it is not hit.
In order to test, use the test below and also add a console.log at the beggining of the calculatePositionOnFocus() function

Test example:

	_test('should navigate focus outside the list from first item using arrow-up key', () => {
		render(
			<div>
				<Button>Hello Button</Button>
				<VirtualList
					clientSize={clientSize}
					dataSize={5}
					itemRenderer={renderItem}
					itemSize={itemSize}
					scrollMode="native"
				/>
			</div>
		);

		jest.useFakeTimers();
		const button = screen.getByRole('button');
		const list = screen.getByRole('list');
		const item0 = list.children.item(0).children.item(0);

		focus(item0);
		expect(currentFocusIndex).toBe(0);

		act(() => jest.advanceTimersByTime(1500));

		pressUpKey(item0);
		screen.debug()
		//expect(button).toHaveFocus();

		jest.useRealTimers();
	});_

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/useEvent-specs.js
> +	return fireEvent.keyUp(elm, {keyCode});
This return statement seems unnecessary.

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-native-specs.js
> +			const {text, subText, source} = items[index];
Order variables please.

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-native-specs.js
> +					horizontalScrollbar="visible"
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-specs.js
> +			const {text, subText, source} = items[index];
Order props please.

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-native-specs.js
> +			const VirtualGridListRoot =  screen.getByRole('list').parentElement.parentElement.parentElement.parentElement;
I do not belive that capital letter is justified here.

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-specs.js
> +			const VirtualGridListRoot =  screen.getByRole('list').parentElement.parentElement.parentElement.parentElement;
I do not belive that capital letter is justified here.

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-specs.js
> +			const VirtualGridListRoot =  screen.getByRole('list').parentElement.parentElement.parentElement.parentElement;
I do not belive that capital letter is justified here.

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-specs.js
> +					onScrollStop={onScrollStop}
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualGridList-specs.js
> +					onScrollStop={fn}
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualList-specs.js
> +					onScrollStop={onScrollStop}
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/VirtualList-specs.js
> +					onScrollStop={fn}
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/useEvent-specs.js
> +			const {name, subText, source} = items[index];
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/useEvent-specs.js
> +				<ImageItem {...rest} label={subText} src={source} onFocus={handlerOnFocus(index)}>
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/useEvent-specs.js
> +				clientSize={clientSize}
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/useEvent-specs.js
> +				clientSize={clientSize}
Order props

2022-12-09 09:48 UTC, alexandrumorariu commented on VirtualList/tests/useEvent-specs.js
> +					dataSize={dataSize}
Order props

2022-12-09 11:04 UTC, alexandrumorariu approved these changes
LGTM

2022-12-09 12:20 UTC, adrian-cocoara-lgp commented on VirtualList/tests/VirtualGridList-specs.js
> +	test('cannot render items when `clientSize` and outer DOM size are not specified', () => {
```suggestion
	test('should not render items when `clientSize` and outer DOM size are not specified', () => {
```

2022-12-09 12:20 UTC, adrian-cocoara-lgp commented on VirtualList/tests/VirtualGridList-specs.js
> +			test('should call onScrollStart once', () => {
```suggestion
			test('should call `onScrollStart` once', () => {
```

2022-12-09 12:20 UTC, adrian-cocoara-lgp commented on VirtualList/tests/VirtualGridList-specs.js
> +			test('should call onScroll once', () => {
```suggestion
			test('should call `onScroll` once', () => {
```

2022-12-09 12:20 UTC, adrian-cocoara-lgp commented on VirtualList/tests/VirtualGridList-specs.js
> +			test('should call onScrollStop once', (done) => {
```suggestion
			test('should call `onScrollStop` once', (done) => {
```

2022-12-09 13:23 UTC, adrian-cocoara-lgp approved these changes
LGTM

2022-12-15 15:48 UTC, stanca-pop-lgp requested changes

2022-12-15 15:48 UTC, stanca-pop-lgp commented on VirtualList/tests/VirtualList-specs.js
> +				itemSize={itemSize}
Please leave empty row before rerender (line 454).

2022-12-15 15:48 UTC, stanca-pop-lgp commented on VirtualList/tests/useEvent-native-specs.js
> +		items = null;
Is assigning null to items which was previously assigned an empty array intended?

2022-12-15 15:48 UTC, stanca-pop-lgp commented on VirtualList/tests/useEvent-native-specs.js
> +
Remove empty line.

2022-12-16 09:58 UTC, daniel-stoian-lgp commented on VirtualList/tests/VirtualGridList-native-specs.js
> +	test('should render only one scrollbar', () => {
i added more description. Regarding the expected result of 2, the structure of the component is the cause. Check also sandstone tests for the similar approach

2022-12-16 13:33 UTC, stanca-pop-lgp approved these changes
LGTM

2022-12-16 13:36 UTC, merged