WRP-6109: Added extra publicClassNames for ImageItem and Popup
enactjs/agate pull request #715
Opened 2023-01-05 14:58 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [x] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
While working on agate-apps repo, it was discovered that ImageItem didn't have any publicClassNames available for customization and Popup didn't have the `content` className public

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added extra publicClassNames for ImageItem and Popup

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-6109

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian [daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com)

2023-01-06 11:28 UTC, adrian-cocoara-lgp approved these changes
LGTM but lets see SWP opinion

2023-01-09 01:34 UTC, seunghoh requested changes

2023-01-09 01:34 UTC, seunghoh commented on CHANGELOG.md
> +- `agate/ImageITem` to have `imageItem`, `caption` and `image` publicClassnames
Typo - agate/ImageItem

2023-01-09 08:17 UTC, daniel-stoian-lgp commented on CHANGELOG.md
> +- `agate/ImageITem` to have `imageItem`, `caption` and `image` publicClassnames
```suggestion
- `agate/ImageItem` to have `imageItem`, `caption` and `image` publicClassnames
```

2023-01-13 12:21 UTC, stanca-pop-lgp approved these changes
LGTM

2023-01-15 11:54 UTC, daniel-stoian-lgp commented
@seunghoh , can you review this PR. your comment was solved. Merging is blocket ATM

2023-01-17 02:15 UTC, seunghoh approved these changes

2023-01-17 08:57 UTC, merged