WPR-8978: Make 'scrollMode' default value as 'native' on Agate components
enactjs/agate pull request #748
Opened 2023-06-23 09:57 UTC by andreitirlalge

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Make `scrollMode` default value as `native` on Scroller, VirtualList, VirtualGridList components

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Scroller, VirtualList and VirtualGridList components now have default scrollMode value as `native'.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-8978

### Comments
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

2023-06-26 17:53 UTC, daniel-stoian-lgp requested changes

2023-06-29 13:05 UTC, andreitirlalge commented on VirtualList/tests/useEvent-translate-specs.js
> +				scrollMode="translate"
I added scrollMode for all test cases and changed the name of the test suite to mention scrollMode

2023-06-29 16:21 UTC, daniel-stoian-lgp commented
please add a changelog
please mark in the pr description that this pr has test cases and that it is a API breaking change

2023-06-29 16:22 UTC, daniel-stoian-lgp reviewed
please add a changelog and mark it in the PR description
please mark in the PR description that this PR has test cases and that it is a API breaking change

2023-07-03 16:18 UTC, daniel-stoian-lgp commented on CHANGELOG.md
> +Changed `scrollMode` default value as `native` on the following components: `Scroller`, `VirtualList` and `VirtualGridList`.
```suggestion
- `agate/Scroller`, `agate/VirtualList` and `agate/VirtualGridList` default value for `scrollMode` to `native`.
```

2023-07-03 16:26 UTC, daniel-stoian-lgp approved these changes

2023-07-04 08:08 UTC, dongsuwon reviewed
I think it's better to remove 'scrollMode=native' in native scroller/virtualList/VirtualGridList unit tests. There are unnecessary codes as changed default value.

2023-08-16 00:03 UTC, dongsuwon commented
LGTM

2023-08-16 00:03 UTC, merged