WRR-1113: Remove data/consumerDecorator and data/providerDecorator
enactjs/agate pull request #810
Opened 2024-09-04 10:40 UTC by paul-beldean-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Remove data/consumerDecorator and data/providerDecorator

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Removed `immer` dependency as it is no longer used.

### Links
[//]: # (Related issues, references)
WRR-1113

### Comments

Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

2024-09-04 13:59 UTC, daniel-stoian-lgp approved these changes

2024-09-05 00:38 UTC, seunghoh requested changes

2024-09-05 00:38 UTC, seunghoh commented on CHANGELOG.md
> +- `immer` dependency
We do not write private apis in the change log. 
Let's revert the changelog.md

2024-09-06 06:12 UTC, seunghoh approved these changes
LGTM

2024-09-06 06:12 UTC, merged