WRR-10798: Fixed redundant variables, missing await, redundant await, deprecated functions
enactjs/agate pull request #824
Opened 2024-12-10 14:02 UTC by alexandrumorariu

### Checklist

* [X] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [X] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Fixed redundant variables, missing await, redundant await, deprecated functions.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRR-10798

### Comments

2024-12-12 14:22 UTC, stanca-pop-lgp approved these changes

2024-12-19 06:10 UTC, seunghoh requested changes
Thanks for the PR, I understand your changes but I'd prefer the original code from a readability perspective. I had a similar discussion with  @daniel-stoian-lgp before. Let's fix only the obvious fault codes. I commented `OK` inline.

2024-12-19 06:10 UTC, seunghoh commented on Dropdown/DropdownList.js
> +		className: ({direction, skin, width, styler}) => styler.append(direction.substring(0, direction.indexOf(' ')), width, {dropdownListWithCustomizedScroller: skin === 'silicon'}),
OK

2024-12-19 06:10 UTC, seunghoh commented on Item/Item.module.less
> +				align-self: @agate-item-indicator-align-self;
OK

2024-12-19 06:10 UTC, seunghoh commented on ThemeDecorator/ThemeDecorator.js
> +import {Component, createContext} from 'react';
OK

2024-12-19 06:10 UTC, seunghoh commented on tests/ui/specs/MediaPlayer/MediaPlayer-specs.js
> +			await Page.delay(1000);
OK

2024-12-19 06:10 UTC, seunghoh commented on tests/ui/specs/MediaPlayer/MediaPlayer-specs.js
> +			await Page.delay(1000);
OK

2024-12-19 06:10 UTC, seunghoh commented on tests/ui/specs/ToggleButton/ToggleButton-Page.js
> +		return browser.execute((el) => el.focus(), `#${this.id}`);
OK

2024-12-19 06:10 UTC, seunghoh commented on tests/ui/specs/RangePicker/RangePicker-specs.js
> +						await browser.pause(500);
Would you explain why we should change 100 -> 500?

2024-12-19 06:10 UTC, seunghoh commented on tests/ui/specs/VirtualList/VirtualList-utils.js
> +		return target.contains(document.elementFromPoint(...targetDown)) || target.contains(document.elementFromPoint(...targetTop));
OK

2024-12-23 07:39 UTC, seunghoh approved these changes
LGTM

2024-12-23 07:39 UTC, merged